### ISSUE TITLE
BYE-030/메인페이지 구현

### ISSUE THREAD

**Issue by jungo0** [codestates-seb/seb44_main_022#47]
## 요구사항 ID

BYE-030

## 요구사항

메인페이지 구현

## 상세 요구사항

- 메인페이지 구현

## TODO
- [x] 메인페이지 구현

**Comment by KimJunpyo** [comment]
레이아웃 완

**Comment by KimJunpyo** [comment]
현재 메인페이지에서 렉걸리는 버그 있음 해결해야함
